# Generated by Django 5.2.4 on 2025-07-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Semanas',
                'ordering': ['numero_semana'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=255)),
                ('meta_cantidad_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('fecha_inicio_programada', models.DateField()),
                ('fecha_fin_programada', models.DateField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.partida')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ReportePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('area_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.areadetrabajo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.empresa')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.partida')),
            ],
            options={
                'verbose_name_plural': 'Reportes de Personal',
            },
        ),
        migrations.CreateModel(
            name='AvanceDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('cantidad_programada_dia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_realizada_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
            ],
            options={
                'verbose_name_plural': 'Avances Diarios',
                'unique_together': {('actividad', 'fecha_reporte')},
            },
        ),
    ]
