# Generated by Django 5.2.4 on 2025-09-19 00:51

import actividades.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Partidas de Actividades',
            },
        ),
        migrations.CreateModel(
            name='PartidaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Partidas de Personal',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de Finalización Estimada')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('temp_max_c', models.FloatField(help_text='Temperatura máxima en °C')),
                ('temp_min_c', models.FloatField(help_text='Temperatura mínima en °C')),
                ('sensacion_max_c', models.FloatField(help_text='Sensación térmica máxima en °C (horario laboral)')),
                ('precipitacion_total_mm', models.FloatField(help_text='Precipitación total del día en mm')),
                ('precipitacion_laboral_mm', models.FloatField(help_text='Precipitación en horario laboral (8am-6pm) en mm')),
                ('precipitacion_no_laboral_mm', models.FloatField(help_text='Precipitación fuera de horario laboral en mm')),
                ('condicion_texto', models.CharField(help_text='Descripción del clima (ej. Neblina)', max_length=100)),
                ('condicion_icono', models.URLField(help_text='URL del ícono del clima')),
            ],
            options={
                'verbose_name': 'Reporte de Clima',
                'verbose_name_plural': 'Reportes de Clima',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Semanas',
                'ordering': ['numero_semana'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Actividad/Categoría')),
                ('meta_cantidad_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Solo llenar para actividades finales (sin hijos). Ej: 66470', max_digits=12, verbose_name='Meta de Cantidad')),
                ('unidad_medida', models.CharField(blank=True, help_text='Ej: m3, Ton, Pza', max_length=50, verbose_name='Unidad de Medida')),
                ('fecha_inicio_programada', models.DateField(blank=True, null=True)),
                ('fecha_fin_programada', models.DateField(blank=True, null=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_actividades', to='actividades.actividad', verbose_name='Categoría Padre')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actividades.partidaactividad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='actividades.proyecto')),
            ],
            options={
                'verbose_name': 'Actividad (WBS)',
                'verbose_name_plural': 'Actividades (WBS)',
                'unique_together': {('nombre', 'padre', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='TipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Retroexcavadora', max_length=100, unique=True)),
                ('partida', models.ForeignKey(blank=True, help_text='Partida a la que suele pertenecer esta maquinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.partidaactividad')),
            ],
            options={
                'verbose_name': 'Tipo de Maquinaria',
                'verbose_name_plural': 'Tipos de Maquinaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AvanceDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('cantidad_realizada_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='actividades.actividad')),
                ('zonas', models.ManyToManyField(blank=True, to='actividades.areadetrabajo', verbose_name='Zonas de Trabajo Aplicables')),
                ('empresa', models.ForeignKey(default=actividades.models.get_default_empresa_pk, on_delete=django.db.models.deletion.PROTECT, to='actividades.empresa', verbose_name='Empresa Contratista')),
            ],
            options={
                'verbose_name_plural': 'Avances Diarios',
                'unique_together': {('actividad', 'fecha_reporte', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='ReportePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('area_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.areadetrabajo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.empresa')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.partidapersonal')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Reportes de Personal',
                'unique_together': {('proyecto', 'fecha', 'empresa', 'cargo', 'partida', 'area_de_trabajo')},
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del reporte')),
                ('cantidad_total', models.PositiveIntegerField(help_text='Número total de equipos de este tipo en el día')),
                ('cantidad_activa', models.PositiveIntegerField(help_text='Número de equipos que están activos/operando')),
                ('cantidad_inactiva', models.PositiveIntegerField(help_text='Número de equipos que están inactivos/en descanso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria o que opera la maquinaria', on_delete=django.db.models.deletion.PROTECT, to='actividades.empresa')),
                ('partida', models.ForeignKey(help_text='Partida en la que se utiliza la maquinaria', on_delete=django.db.models.deletion.PROTECT, to='actividades.partidaactividad')),
                ('zona_trabajo', models.ForeignKey(help_text='Zona de la obra donde se encuentra', on_delete=django.db.models.deletion.PROTECT, to='actividades.areadetrabajo')),
                ('tipo_maquinaria', models.ForeignKey(help_text='Tipo de maquinaria reportada', on_delete=django.db.models.deletion.PROTECT, to='actividades.tipomaquinaria')),
            ],
            options={
                'verbose_name': 'Reporte Diario de Maquinaria',
                'verbose_name_plural': 'Reportes Diarios de Maquinaria',
                'ordering': ['-fecha', 'partida', 'tipo_maquinaria'],
                'unique_together': {('fecha', 'tipo_maquinaria', 'partida', 'empresa', 'zona_trabajo')},
            },
        ),
    ]
