# Generated by Django 5.2.4 on 2025-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='meta_cantidad_total',
            new_name='meta_general',
        ),
        migrations.RenameField(
            model_name='avancediario',
            old_name='cantidad_realizada_dia',
            new_name='cantidad_general',
        ),
        migrations.RemoveField(
            model_name='avancediario',
            name='zonas',
        ),
    ]
