# Generated by Django 5.2.4 on 2025-07-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Partidas de Personal',
            },
        ),
        migrations.RenameModel(
            old_name='Partida',
            new_name='PartidaActividad',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='partidaactividad',
            options={'verbose_name_plural': 'Partidas de Actividades'},
        ),
        migrations.AlterField(
            model_name='reportepersonal',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.partidapersonal'),
        ),
    ]
