# Generated by Django 5.2.4 on 2025-07-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_partidapersonal_rename_partida_partidaactividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Retroexcavadora', max_length=100, unique=True)),
                ('partida', models.ForeignKey(blank=True, help_text='Partida a la que suele pertenecer esta maquinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.partidaactividad')),
            ],
            options={
                'verbose_name': 'Tipo de Maquinaria',
                'verbose_name_plural': 'Tipos de Maquinaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del reporte')),
                ('cantidad_total', models.PositiveIntegerField(help_text='Número total de equipos de este tipo en el día')),
                ('cantidad_activa', models.PositiveIntegerField(help_text='Número de equipos que están activos/operando')),
                ('cantidad_inactiva', models.PositiveIntegerField(help_text='Número de equipos que están inactivos/en descanso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria o que opera la maquinaria', on_delete=django.db.models.deletion.PROTECT, to='actividades.empresa')),
                ('partida', models.ForeignKey(help_text='Partida en la que se utiliza la maquinaria', on_delete=django.db.models.deletion.PROTECT, to='actividades.partidaactividad')),
                ('zona_trabajo', models.ForeignKey(help_text='Zona de la obra donde se encuentra', on_delete=django.db.models.deletion.PROTECT, to='actividades.areadetrabajo')),
                ('tipo_maquinaria', models.ForeignKey(help_text='Tipo de maquinaria reportada', on_delete=django.db.models.deletion.PROTECT, to='actividades.tipomaquinaria')),
            ],
            options={
                'verbose_name': 'Reporte Diario de Maquinaria',
                'verbose_name_plural': 'Reportes Diarios de Maquinaria',
                'ordering': ['-fecha', 'partida', 'tipo_maquinaria'],
                'unique_together': {('fecha', 'tipo_maquinaria', 'partida', 'empresa', 'zona_trabajo')},
            },
        ),
    ]
