# Generated by Django 5.2.4 on 2025-09-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_renombrar_campos_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='meta_general',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usar si la meta no se desglosa por zona. Ej: 66470', max_digits=12, null=True, verbose_name='Meta General'),
        ),
        migrations.AlterField(
            model_name='avancediario',
            name='cantidad_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cantidad General'),
        ),
        migrations.CreateModel(
            name='AvancePorZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad por Zona')),
                ('avance_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_por_zona', to='actividades.avancediario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.areadetrabajo', verbose_name='Zona de Trabajo')),
            ],
            options={
                'verbose_name': 'Avance por Zona',
                'verbose_name_plural': 'Avances por Zona',
                'unique_together': {('avance_diario', 'zona')},
            },
        ),
        migrations.AddField(
            model_name='avancediario',
            name='zonas_avance',
            field=models.ManyToManyField(related_name='avances_diarios', through='actividades.AvancePorZona', to='actividades.areadetrabajo', verbose_name='Desglose de Avance por Zona'),
        ),
        migrations.CreateModel(
            name='MetaPorZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta por Zona')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_por_zona', to='actividades.actividad')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.areadetrabajo', verbose_name='Zona de Trabajo')),
            ],
            options={
                'verbose_name': 'Meta por Zona',
                'verbose_name_plural': 'Metas por Zona',
                'unique_together': {('actividad', 'zona')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='zonas_meta',
            field=models.ManyToManyField(related_name='actividades_meta', through='actividades.MetaPorZona', to='actividades.areadetrabajo', verbose_name='Desglose de Metas por Zona'),
        ),
    ]
