# Generated by Django 5.2.4 on 2025-08-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_carga_datos_iniciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancediario',
            name='cantidad_programada_dia',
        ),
        migrations.AddField(
            model_name='reportepersonal',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.proyecto'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actividades.partidaactividad'),
        ),
        migrations.AlterField(
            model_name='avancediario',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='actividades.actividad'),
        ),
        migrations.AlterUniqueTogether(
            name='reportepersonal',
            unique_together={('proyecto', 'fecha', 'empresa', 'cargo', 'partida', 'area_de_trabajo')},
        ),
    ]
