# Generated by Django 5.2.4 on 2025-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_modelos_de_registro_hibridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaporzona',
            name='fecha_fin_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metaporzona',
            name='fecha_inicio_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
