# Generated by Django 5.2.4 on 2025-08-13 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_remove_avancediario_cantidad_programada_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportepersonal',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.proyecto'),
        ),
    ]
