# Generated by Django 5.2.4 on 2025-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_poblar_semanas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteClima',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('temp_max_c', models.FloatField(help_text='Temperatura máxima en °C')),
                ('temp_min_c', models.FloatField(help_text='Temperatura mínima en °C')),
                ('sensacion_max_c', models.FloatField(help_text='Sensación térmica máxima en °C (horario laboral)')),
                ('precipitacion_total_mm', models.FloatField(help_text='Precipitación total del día en mm')),
                ('precipitacion_laboral_mm', models.FloatField(help_text='Precipitación en horario laboral (8am-6pm) en mm')),
                ('precipitacion_no_laboral_mm', models.FloatField(help_text='Precipitación fuera de horario laboral en mm')),
                ('condicion_texto', models.CharField(help_text='Descripción del clima (ej. Neblina)', max_length=100)),
                ('condicion_icono', models.URLField(help_text='URL del ícono del clima')),
            ],
            options={
                'verbose_name': 'Reporte de Clima',
                'verbose_name_plural': 'Reportes de Clima',
                'ordering': ['-fecha'],
            },
        ),
    ]
