# Generated by Django 5.2.4 on 2025-10-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_poblar_tabla_semanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='meta_general',
        ),
        migrations.RemoveField(
            model_name='avancediario',
            name='cantidad_general',
        ),
    ]
