# Generated by Django 5.2.4 on 2025-08-21 23:26

import actividades.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_reportepersonal_proyecto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avancediario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avancediario',
            name='empresa',
            field=models.ForeignKey(default=actividades.models.get_default_empresa_pk, on_delete=django.db.models.deletion.PROTECT, to='actividades.empresa', verbose_name='Empresa Contratista'),
        ),
        migrations.AlterUniqueTogether(
            name='avancediario',
            unique_together={('actividad', 'fecha_reporte', 'empresa')},
        ),
    ]
