# Generated by Django 5.2.4 on 2025-09-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_avancediario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancediario',
            name='zonas',
            field=models.ManyToManyField(blank=True, to='actividades.areadetrabajo', verbose_name='Zonas de Trabajo Aplicables'),
        ),
    ]
