# Generated by Django 5.2.4 on 2025-10-24 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_mover_datos_generales_a_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoConstructivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Proceso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proceso Constructivo',
                'verbose_name_plural': 'Procesos Constructivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Elemento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Elemento Constructivo',
                'verbose_name_plural': 'Tipos de Elementos Constructivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PasoProcesoTipoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden en la Secuencia')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.procesoconstructivo')),
                ('tipo_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_proceso', to='actividades.tipoelemento')),
            ],
            options={
                'verbose_name': 'Paso de Proceso por Tipo',
                'verbose_name_plural': 'Pasos de Proceso por Tipo',
                'ordering': ['tipo_elemento', 'orden'],
                'unique_together': {('tipo_elemento', 'proceso', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ElementoConstructivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(db_index=True, help_text='El ID único que coincide con el modelo BIM (Navisworks/Revit).', max_length=255, unique=True, verbose_name='Identificador Único (BIM ID)')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Adicional')),
                ('tipo_elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='actividades.tipoelemento')),
            ],
            options={
                'verbose_name': 'Elemento Constructivo',
                'verbose_name_plural': 'Elementos Constructivos',
                'ordering': ['identificador_unico'],
            },
        ),
        migrations.CreateModel(
            name='AvanceProcesoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de Finalización')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_proceso', to='actividades.elementoconstructivo')),
                ('paso_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.pasoprocesotipoelemento')),
            ],
            options={
                'verbose_name': 'Avance de Proceso por Elemento',
                'verbose_name_plural': 'Avances de Proceso por Elemento',
                'ordering': ['elemento', 'paso_proceso__orden'],
                'unique_together': {('elemento', 'paso_proceso')},
            },
        ),
    ]
