# Generated by Django 5.2.4 on 2025-11-07 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_procesoconstructivo_tipoelemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoconstructivo',
            name='identificador_unico',
            field=models.CharField(db_index=True, help_text='El identificador legible por humanos (ej. ZA-B5) que se usará para buscar.', max_length=255, unique=True, verbose_name='Código de Ejes / ID Humano'),
        ),
        migrations.CreateModel(
            name='ElementoBIM_GUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_bim', models.CharField(db_index=True, help_text='El GUID único inmutable del modelo BIM (ej. 1a2b3c4d-...).', max_length=255, unique=True, verbose_name='Identificador BIM (GUID)')),
                ('elemento_constructivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guids_bim', to='actividades.elementoconstructivo', verbose_name='Elemento Constructivo (Ejes)')),
            ],
            options={
                'verbose_name': 'GUID de Elemento BIM',
                'verbose_name_plural': 'GUIDs de Elementos BIM',
                'ordering': ['elemento_constructivo', 'identificador_bim'],
            },
        ),
    ]
