# Generated by Django 5.2.4 on 2025-11-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_procesoconstructivo_tipoelemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoconstructivo',
            name='identificador_bim',
            field=models.CharField(blank=True, db_index=True, help_text='El ID único inmutable del modelo BIM (ej. 1234567).', max_length=255, null=True, unique=True, verbose_name='Identificador BIM (Revit/Navis)'),
        ),
        migrations.AlterField(
            model_name='elementoconstructivo',
            name='identificador_unico',
            field=models.CharField(db_index=True, help_text='El identificador legible por humanos (ej. ZA-B5) que se usará para buscar.', max_length=255, unique=True, verbose_name='Código de Ejes / ID Humano'),
        ),
    ]
