# Generated by Django 5.2.4 on 2026-01-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_elementoconstructivo_identificador_unico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Actividad / Zona')),
                ('fecha_inicio_prog', models.DateField(blank=True, null=True, verbose_name='Inicio Programado')),
                ('fecha_fin_prog', models.DateField(blank=True, null=True, verbose_name='Fin Programado')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True, verbose_name='Inicio Real')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fin Real')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tareas', to='actividades.cronograma')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='actividades.proyecto')),
            ],
            options={
                'verbose_name': 'Actividad de Cronograma',
                'verbose_name_plural': 'Cronograma (Project)',
                'ordering': ['fecha_inicio_prog', 'id'],
            },
        ),
    ]
