# Generated by Django 5.2.4 on 2026-01-13 00:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_cronograma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='tareas_cronograma', to='actividades.areadetrabajo', verbose_name='Zonas Aplicables'),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Observación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre / Título de la Observación')),
                ('comentario', models.TextField(verbose_name='Descripción / Comentario')),
                ('resuelto', models.BooleanField(default=False, verbose_name='¿Resuelto?')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.areadetrabajo', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Observación de Campo',
                'verbose_name_plural': 'Observaciones de Campo',
                'ordering': ['-fecha', 'zona'],
                'unique_together': {('fecha', 'zona', 'nombre')},
            },
        ),
    ]
