# Generated by Django 5.2.4 on 2026-01-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_cronograma_zonas_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia_observaciones/', verbose_name='Evidencia Fotográfica'),
        ),
    ]
