# Generated by Django 5.2.4 on 2026-01-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_observacion_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['id'], 'verbose_name': 'Actividad de Cronograma', 'verbose_name_plural': 'Cronograma (Jerarquía)'},
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='tareas_cronograma_legacy', to='actividades.areadetrabajo', verbose_name='Zonas Aplicables (Legacy)'),
        ),
        migrations.CreateModel(
            name='CronogramaPorZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_prog', models.DateField(blank=True, null=True, verbose_name='Inicio Programado')),
                ('fecha_fin_prog', models.DateField(blank=True, null=True, verbose_name='Fin Programado')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True, verbose_name='Inicio Real')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fin Real')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_zona', to='actividades.cronograma')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas_zona', to='actividades.areadetrabajo')),
            ],
            options={
                'verbose_name': 'Detalle de Cronograma por Zona',
                'verbose_name_plural': 'Detalles de Cronograma por Zona',
                'ordering': ['fecha_inicio_prog'],
                'unique_together': {('tarea', 'zona')},
            },
        ),
    ]
