# Generated by Django 5.2.4 on 2026-01-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_migrar_datos_zonas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='fecha_fin_prog',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='fecha_fin_real',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='fecha_inicio_prog',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='fecha_inicio_real',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='zonas',
        ),
    ]
