# Generated by Django 5.2.4 on 2026-01-31 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_remove_cronograma_fecha_fin_prog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='resuelto',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='resuelto_por',
        ),
        migrations.AddField(
            model_name='observacion',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', '🔴 No Iniciado'), ('proceso', '🟡 En Progreso'), ('resuelto', '🟢 Resuelto')], default='pendiente', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Última Actualización'),
        ),
    ]
